### ISSUE TITLE
Add a decompressor for tar files

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollmoves#38]
Currently the available on-the-fly decompression methods are `bzip2` and `xrit`. Decompressor for `.tar`, `.tar.gz`, `.tgz` and `.tar.bz2` files is needed. The `tarfile` package seems to be a good candidate for this.

**Comment by mraspaud** [comment]
There is an untaring feature in the move_it_server...

**Comment by pnuu** [comment]
Is there? I went through `server.py` before creating this issue and found only those two decompressors.

**Comment by mraspaud** [comment]
Oh, sorry, it's on the client side
https://github.com/pytroll/trollmoves/blob/master/trollmoves/client.py#L197-L208

**Comment by mraspaud** [comment]
It actually makes more sense to unpack after transfering the file. However, I think what we have now just handles `.tar`, not the zipped versions of if.

**Comment by mraspaud** [comment]
oh, looks like it actually does: `Open for reading with transparent compression (recommended).`

**Comment by pnuu** [comment]
Yes, was just about to comment that the unpacking in `tarfile` works by default for all the versions I listed above.

So maybe we should move all the other decompressors on the client side?

**Comment by mraspaud** [comment]
ah, but we would need to add a couple more extension to this: https://github.com/pytroll/trollmoves/blob/master/trollmoves/client.py#L211

**Comment by pnuu** [comment]
Isn't that just the name of the "unpacker" in the config?

**Comment by mraspaud** [comment]
it's also used to check the ending of the file: https://github.com/pytroll/trollmoves/blob/master/trollmoves/client.py#L264

**Comment by mraspaud** [comment]
indeed, we should have all decompressors available on the client side, but I'm not convinced we should remove them from the server side. Could it be that we sometime don't really have control over the client side ?

**Comment by pnuu** [comment]
Agreed. I'll create another ticket for the unpack'ability on both client and server sides, and close this one.
