### ISSUE TITLE
Make unpacking possible on both client and server

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollmoves#39]
Based on discussion on https://github.com/pytroll/trollmoves/issues/38 all the decompressors should be available both on the server and client sides. Currently client can handle only `.tar` files, and server `bzip2` and `XRIT` compressed files. In the end both should handle all of these, and also `.tar.gz`, `.tgz`, `.tar.bz2` etc. files.

**Comment by mraspaud** [comment]
@tecnavia-dev you might be interested in this.

**Comment by pnuu** [comment]
This should have been closed by #49 and #52
