### ISSUE TITLE
 connection lifetime should be configurable for all transfer methods

### ISSUE THREAD

**Issue by peters77** [pytroll/trollmoves#54]
I have problems copying large files via scp (e.g. Sentinel tar files) and the conncetion timed out (lifetime 30s?) before the file is transfered and unpacked at the cilent side. 

`21:34:57,765 DEBUG    trollmoves.movers] Successfully connected to pc as user
….`
`21:35:27,767 DEBUG    trollmoves.movers] Closing connection to user@pc:None`

It would be nice to set the lifetime in the config file for each transfer method to observe bigger transfer times.

**Comment by TAlonglong** [comment]
It is. For the client to can configure like this:
```
transfer_req_timeout=<seconds>
req_timeout=<seconds>
```

And for the server:
```
connection_uptime = <seconds> defaults to 30
```
