### ISSUE TITLE
Trollmoves Client leaks memory

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollmoves#88]
Trollmoves Client seems to be leaking, or not releasing, memory.

This is a screen capture from our Nagios service:

![trollmoves_client_memory_usage](https://user-images.githubusercontent.com/3170788/113819741-6884ac00-9782-11eb-8185-8a09f75d0375.png)

The server has altogether 16 Trollmoves Clients running, but it seems only one of them accumulates a significant amount of memory and restarting that one will release the memory. The config in question looks like this:

```ini
[DEFAULT]
nameservers = processing_host.fmi.fi
login = user
destination = scp://io_host.fmi.fi/satellite/data/oper/nwcsaf_geo/v2018/
delete = False

[nwc_saf_geo_asii-gw]
publish_port = 40202
providers = nwc_host.fmi.fi:9011
topic = /nwc_geo/0deg/asii-gw

[nwc_saf_geo_asii-sat]
publish_port = 40203
providers = nwc_host.fmi.fi:9011
topic = /nwc_geo/0deg/asii-sat

[nwc_saf_geo_asii-tw]
...
```
repeating for every 22 NWC SAF GEO products with no duplicates.

The Client is started, similar to others, with:

```bash
move_it_client.py -v $HOME/config_files/trollmoves_client_geo_nwc_msg_0deg.ini
```

This is by far the largest setup I have, the second largest has four sections

**Comment by TAlonglong** [comment]
I see similar https://snapshot.raintank.io/dashboard/snapshot/CDYKkgH36M8vGfXtmnFDly9Yyhtcqixc
Only 2 weeks of data but  a restart of the client yesterday gave this memory graph.

**Comment by mraspaud** [comment]
Any clue if this has been introduced recently?

**Comment by pnuu** [comment]
I just noticed this March 29, couple weeks after the above chain was taken to use. I have one PR merged locally (#84, which is still a draft), but otherwise I'm running the latest release 0.6.2 from December. Some of the other Clients are still using the official 0.6.2.

**Comment by pnuu** [comment]
In some of the chains I get *only* log messages like `Remove uid 9d0d6e49a59cb66166a833cb590fee7f: []`. These are logged [here](https://github.com/pytroll/trollmoves/blob/master/trollmoves/client.py#L253), and would indicate these are never cleared from the ongoing transfers. The above NWC SAF GEO chain is one of these. But there is also a chain for Himawari-8 transfers that has been running for 70 days without accumulating RAM.

**Comment by pnuu** [comment]
Never mind. There are other places where the `uid` is removed from the `ongoing_transfers` list where the cleaning is not logged.

**Comment by pnuu** [comment]
... which are calling the same method, so they should be logged.

**Comment by pnuu** [comment]
Based on the log messages, the files are published twice on our NWC SAF GEO processing server. That happens if something, possibly the processing software, is touching the files in a way that creates a new `inotify`message from the kernel. On the latter round, the received message is added to the ongoing messages, but never deleted: https://github.com/pytroll/trollmoves/blob/master/trollmoves/client.py#L549-L556

I'm adding a local change that will clear the message from the `ongoing_transfers` to see if that's it.

**Comment by pnuu** [comment]
The fix I attempted in #89 didn't help. I start debugging on live process with `pyrasite`.

**Comment by pnuu** [comment]
Using `pyrasite` I could verify the `ongoing_transfers` dictionary is empty and that the `file_cache` is at it should:
```bash
$ pyrasite-shell 10448
>>> from trollmoves.client import ongoing_transfers
>>> print(len(ongoing_transfers))
0
>>> from trollmoves.client import file_cache
>>> print(len(file_cache))
2169
```

**Comment by pnuu** [comment]
I'm completely out of other ideas. I'll convert the draft to a proper PR and unlink it. If we get new ideas for a real fix lets open a new one.
